# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: EnsembleControl
author: Johannes Milz
copyright: "2024"
only_build_toc_files : false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Information about where the book exists on the web
repository:
  url: https://github.com/milzj/EnsembleControl # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"

html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"

  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'


exclude_patterns: ["README.md","src/*", "test/*",
"CONTRIBUTING.md", ".pytest_cache/*", "*.py"]
