name: Build package documentation

on:
  pull_request:
    branches:
      - "main"

  # This workflow can be executed inside another workfow file
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Directory that will be uploaded as an artifact
      PUBLISH_DIR: ./_build/html

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install ".[test,docs]"

      - name: Build docs
        run: 	jupyter book build -W .

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error
  
