name: Check package formatting

on:
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main
  
  # This workflow can be executed inside another workfow file
  workflow_call:

    
jobs:
  check-code:
    # This skips running the test if '[ci skip]' or '[skip ci]' is in the commit message
    # if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"

    # Choose which operating system to run on, for more options see:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        # Test with a wide range of python versions
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install code"
        run: python -m pip install .[test]

      - name: Flake8 code
        run: python -m flake8

      - name: Mypy check
        run: python -m mypy
