name: Deploy to github pages

on:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:  
  # Check formatting of code with local workflow
  check-formatting:
    uses: ./.github/workflows/check_formatting.yml

  # Run all tests on various platforms and upload coverage report
  run-coverage:
    uses: ./.github/workflows/test_package.yml

  # Build documentation/website. Will be downloaded in first step
  build-docs:
    uses: ./.github/workflows/build_docs.yml

  deploy:
    needs: [check-formatting, run-coverage, build-docs]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download docs artifact
        # docs artifact is uploaded by build-docs job
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: "./public"

      - name: Download docs artifact
        # docs artifact is uploaded by build-docs job
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: "./public/code-coverage-report"
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./public"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
