name: Run package tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

  # This workflow can be executed inside another workfow file
  workflow_call:

  # Allows triggering the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_code:
    # This code depends on the result of check-code
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v7

      - name: "Install ensemblecontrol"
        run: pip install .[test]

      - name: Run tests
        run: python -m pytest -xvs

      - name: Upload coverage report as artifact
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-report
          path: htmlcov
          if-no-files-found: error
