name: Run package tests

on:

  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

  # This workflow can be executed inside another workfow file
  workflow_call:

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
  
jobs:
  test_code:
    # This code depends on the result of check-code
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v3

      - name: "Install mypackage"
        run: pip install .[test]

      - name: Run tests
        run: python -m pytest -xvs

      - name: Upload coverage report as artifact
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
          if-no-files-found: error
